name: bmi_calculator
description: A BMI calculator app developed with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.0.3
  intl: ^0.17.0
  shared_preferences: ^2.0.7

dev_dependencies:
  build_runner: ^2.3.0
  dart_code_metrics: ^4.19.1
  change_app_package_name: ^0.1.3
  flutter_launcher_icons: 0.11.0
  flutter_native_splash: ^2.2.16
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  test: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  # adaptive_icon_background: "#AA0B8EE9"
  # adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
flutter_native_splash:
  android: true
  color: "#FFFFFF"
  image: assets/images/logo.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
